#! /bin/bash

# Copyright (c) the LinBox group
# This file is part of LinBox (and probably stolen here and there)
# see COPYING for licence

prefix=/Users/nguyentrinh/Documents/GitHub/wiedemann-analyzer//linbox-1.7.1
exec_prefix=${prefix}
includedir=${prefix}/include
libdir=${exec_prefix}/lib

major=`echo 1.7.1 | cut -d'.' -f1`
minor=`echo 1.7.1 | cut -d'.' -f2`
micro=`echo 1.7.1 | cut -d'.' -f3`
decvr=$((((($major*100)+$minor)*100)+$micro))


cflags=false
libs=false


usage()
{
    cat <<EOF
Usage: linbox-config [OPTION]

Known values for OPTION are:

  --prefix		show Linbox installation prefix 
  --libs		print library linking information
  --cflags		print pre-processor and compiler flags
  --help		display this help and exit
  --version		output version information string (eg 1.7.1)
  --decimal-version	output version information number (eg $decvr)

EOF

    exit $1
}

if test $# -eq 0; then
    usage 1
fi

while test $# -gt 0; do
    case "$1" in
    -*=*) optarg=`echo "$1" | sed 's/[-_a-zA-Z0-9]*=//'` ;;
    *) optarg= ;;
    esac

    case "$1" in
    --prefix=*)
	prefix=$optarg
	;;

    --prefix)
	echo $prefix
	;;

    --version)
	echo 1.7.1
	exit 0
	;;

    --decimal-version)
	echo $decvr
	exit 0
	;;

    --help)
	usage 0
	;;

    --cflags)
	echo -I${includedir} -I/Users/nguyentrinh/Documents/GitHub/wiedemann-analyzer/fflas-ffpack-2.5.0/include -I/Users/nguyentrinh/Documents/GitHub/wiedemann-analyzer/OpenBLAS-0.3.30/include -std=gnu++11 -I/Users/nguyentrinh/Documents/GitHub/wiedemann-analyzer/givaro-4.2.1/include       
	;;

    --libs)
	echo -I${libdir} -llinbox       -L/Users/nguyentrinh/Documents/GitHub/wiedemann-analyzer/OpenBLAS-0.3.30/lib -lopenblas -L/Users/nguyentrinh/Documents/GitHub/wiedemann-analyzer/givaro-4.2.1/lib -lgivaro -lgmpxx -lgmp
	;;

    *)
	usage
	exit 1
	;;
    esac
    shift
done
echo

exit 0
